name: CraftingBlocker
version: 1.0
main: pl.twojastrona.craftingblocker.CraftingBlocker
api-version: 1.8
author: Uzierek
description: Plugin blokujący pola craftingu w ekwipunku gracza

commands:

permissions:
